# Generated by Django 6.0.7 on 2026-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(help_text="URL identifier (e.g., 'django-rest-api-tips')", unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in blog list')),
                ('content', models.TextField(help_text='Full blog post content (Markdown supported)')),
                ('image', models.URLField(blank=True, help_text='Cover image URL', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
